version: "3"

services:
  memgraph:
    image: memgraph/memgraph:latest
    volumes:
        - "./memgraph/query_modules:/usr/lib/memgraph/query_modules"
    entrypoint: ["/usr/lib/memgraph/memgraph", "--telemetry-enabled=false", "--kafka-bootstrap-servers=ec2-34-245-33-31.eu-west-1.compute.amazonaws.com:9092", "--log-level=TRACE"]
    ports:
        - "7687:7687"

  backend:
    build:
      context: backend
    depends_on:
      - memgraph
    ports:
      - "5000:5000"
